### ISSUE TITLE
Add it to awesome-mcp-servers

### ISSUE THREAD

**Issue by punkpeye** [linux-china/mcp-rs-template#1]
Considering adding your tool to:

https://github.com/punkpeye/awesome-mcp-servers/

You can create a PR directly from README.md.

Just a suggestion!

**Comment by linux-china** [comment]
Thanks.  https://github.com/punkpeye/awesome-mcp-servers/pull/12  already.

**Comment by punkpeye** [comment]
Awesome. Thanks!
